-- SQLite

SELECT L.*, CU.NAME AS 'NOME CLIENTE', CA.NAME AS 'NOME CARRO', E.NAME AS 'NOME FUNCIONARIO' FROM LOCATIONS AS L
JOIN CUSTOMERS AS CU ON (L.CUSTOMER_ID = CU.ID)
JOIN CARS AS CA ON (L.CAR_ID = CA.ID)
JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID);